jobs:
  finalize:
    name: Finalize
    needs:
    - publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"carvel-succeed\"\n\
          }\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Notify Build Failure Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"carvel-failed\"\n\
          }\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
  prepare:
    name: Prepare
    outputs:
      ctr-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      dataflow-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      server-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      skipper-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
  publish:
    name: Publish
    needs:
    - prepare
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: ./.github/workflows/common-carvel.yml
    with:
      ctr-version: ${{ needs.prepare.outputs.dataflow-version }}
      dataflow-version: ${{ needs.prepare.outputs.dataflow-version }}
      package-bundle: springcloud/scdf-oss-package
      package-name: scdf
      package-version: ${{ needs.prepare.outputs.server-version }}
      repository-bundle: springcloud/scdf-oss-repo
      server-repository: springcloud/spring-cloud-dataflow-server
      server-version: ${{ needs.prepare.outputs.server-version }}
      skipper-repository: springcloud/spring-cloud-skipper-server
      skipper-version: ${{ needs.prepare.outputs.skipper-version }}
name: Carvel Worker
on:
  repository_dispatch:
    types: trigger-ga___carvel-worker.yml
