jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
    - continue-on-error: true
      name: Extract Build Id
      run: 'echo JFROG_CLI_BUILD_NAME=${{ github.event.inputs.buildName }} >> $GITHUB_ENV

        echo JFROG_CLI_BUILD_NUMBER=${{ github.event.inputs.buildNumber }} >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Download Release Files
      run: "jfrog rt download \\\n  --spec .github/release-files-spec.json \\\n  --spec-vars\
        \ \"buildname=$JFROG_CLI_BUILD_NAME;buildnumber=$JFROG_CLI_BUILD_NUMBER\"\n"
    - continue-on-error: true
      uses: jvalkeal/nexus-sync@v0
      with:
        close: true
        create: true
        generate-checksums: true
        password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
        pgp-sign: true
        pgp-sign-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        pgp-sign-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        release: true
        staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
        upload: true
        url: ${{ secrets.OSSRH_URL }}
        username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
name: Central Sync
on:
  repository_dispatch:
    types: trigger-ga___cental-sync.yml
