jobs:
  prepare:
    name: Prepare
    outputs:
      dataflow-version: ${{ env.DATAFLOW_VERSION }}
      package-version: ${{ env.PACKAGE_VERSION }}
      skipper-version: ${{ env.SKIPPER_VERSION }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: target
        ref: ${{ inputs.branch && inputs.branch || github.ref }}
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - continue-on-error: true
      uses: carvel-dev/setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup npm
      run: npm install
      shell: bash
      working-directory: src/carvel
    - continue-on-error: true
      name: npm ci
      run: npm ci
      shell: bash
      working-directory: src/carvel
    - continue-on-error: true
      name: Lint
      run: npm run format-check
      shell: bash
      working-directory: src/carvel
    - continue-on-error: true
      name: Test
      run: npm test
      shell: bash
      working-directory: src/carvel
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      name: Configure Env
      run: "ROOT=$(realpath $PWD)\npushd target\n  source $ROOT/.github/workflows/export-app-versions.sh\n\
        \  echo DATAFLOW_VERSION=$DATAFLOW_VERSION >> $GITHUB_ENV\n  echo SKIPPER_VERSION=$SKIPPER_VERSION\
        \ >> $GITHUB_ENV\n  if [ \"${{ inputs.package_version }}\" != \"\" ]; then\n\
        \    echo PACKAGE_VERSION=${{ inputs.package_version }} >> $GITHUB_ENV\n \
        \ else\n    echo PACKAGE_VERSION=$DATAFLOW_VERSION >> $GITHUB_ENV\n  fi\n\
        popd\n"
  publish:
    name: Publish
    needs:
    - prepare
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: ./.github/workflows/common-carvel.yml
    with:
      ctr-version: ${{ needs.prepare.outputs.dataflow-version }}
      dataflow-version: ${{ needs.prepare.outputs.dataflow-version }}
      package-bundle: springcloud/scdf-oss-package
      package-name: scdf
      package-version: ${{ needs.prepare.outputs.package-version }}
      repository-bundle: springcloud/scdf-oss-repo
      server-repository: springcloud/spring-cloud-dataflow-server
      server-version: ${{ needs.prepare.outputs.dataflow-version }}
      skipper-repository: springcloud/spring-cloud-skipper-server
      skipper-version: ${{ needs.prepare.outputs.skipper-version }}
name: CI Carvel
on:
  repository_dispatch:
    types: trigger-ga___ci-carvel.yml
