jobs:
  test:
    name: DB IT on ${{ matrix.group }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      name: Login dockerhub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      name: 'Action: Run Db IT'
      run: "mvn \\\n  -s .settings.xml \\\n  -pl spring-cloud-dataflow-server \\\n\
        \  -Dgroups=${{ matrix.group }} \\\n  -Pfailsafe \\\n  --batch-mode \\\n \
        \ integration-test\n"
    - continue-on-error: true
      id: test_report
      if: ${{ success() || failure() }}
      name: Integration Test Report for ${{ matrix.group }}
      uses: dorny/test-reporter@v1
      with:
        list-tests: failed
        name: Integration Tests - ${{ matrix.group }}
        path: '**/failsafe-reports/*IT.xml'
        reporter: java-junit
    - continue-on-error: true
      name: Publish Test Url for ${{ matrix.group }}
      run: 'echo "Test report for ${{ matrix.group }} published at ${{ steps.test_report.outputs.url_html
        }}"

        '
      shell: bash
    - continue-on-error: true
      if: ${{ success() || failure() }}
      name: 'Action: Upload Unit Test Results'
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: ${{ matrix.group }}-test-results-surefire
        path: ./**/target/surefire-reports/**/*.*
        retention-days: 7
    - continue-on-error: true
      if: ${{ success() || failure() }}
      name: 'Action: Upload Integration Test Results'
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: ${{ matrix.group }}-test-results-failsafe
        path: ./**/target/failsafe-reports/**/*.*
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        group:
        - mariadb
        - postgres
name: CI IT Database
on:
  repository_dispatch:
    types: trigger-ga___ci-it-db.yml
