jobs:
  images:
    name: Build and Publish Images
    needs:
    - prepare
    secrets:
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
    uses: ./.github/workflows/build-images.yml
    with:
      delete-tags: ${{ inputs.delete-tags == 'true' }}
      version: ${{ needs.prepare.outputs.version }}
  prepare:
    name: Prepare Build
    outputs:
      version: ${{ env.VERSION }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ inputs.version == null || inputs.version == '' }}
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ inputs.version == null || inputs.version == '' }}
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      if: ${{ inputs.version == null || inputs.version == '' }}
      name: Version from POM
      run: echo "VERSIONS=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
        >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      if: ${{ inputs.version != null && inputs.version != '' }}
      name: Version from Input
      run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
name: CI - Images
on:
  repository_dispatch:
    types: trigger-ga___ci-images.yml
