jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: jlumbroso/free-disk-space@main
      with:
        docker-images: false
        dotnet: false
        large-packages: false
        swap-storage: false
        tool-cache: false
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      name: Build
      run: './mvnw -B -s .github/settings.xml clean install

        '
      shell: bash
      timeout-minutes: 75
    - continue-on-error: true
      if: failure()
      name: Capture Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Unit Tests
        path: '**/surefire-reports/*.xml'
        retention-days: 3
  done:
    needs:
    - scan
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Done
      run: echo "::info ::Done"
      shell: bash
  scan:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        format: table
        ignore-unfixed: true
        scan-type: fs
        severity: CRITICAL,HIGH
    - continue-on-error: true
      name: Scanned
      run: echo "::info ::Scanned"
      shell: bash
name: CI PRs
on:
  repository_dispatch:
    types: trigger-ga___ci-pr.yml
