env:
  MAVEN_THREADS: -T 1
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    if: github.repository_owner == 'spring-cloud'
    outputs:
      version: ${{ env.spring_cloud_dataflow_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2-

          '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
    - continue-on-error: true
      name: Login dockerhub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      name: Configure JFrog Cli
      run: "jfrog rt mvnc \\\n  --server-id-resolve=repo.spring.io \\\n  --server-id-deploy=repo.spring.io\
        \ \\\n  --repo-resolve-releases=libs-milestone \\\n  --repo-resolve-snapshots=libs-snapshot\
        \ \\\n  --repo-deploy-releases=libs-release-local \\\n  --repo-deploy-snapshots=libs-snapshot-local\n\
        echo JFROG_CLI_BUILD_NAME=spring-cloud-dataflow-main >> $GITHUB_ENV\necho\
        \ JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV\necho spring_cloud_dataflow_version=$(mvn\
        \ help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Build and Publish
      run: 'mvn clean

        ./spring-cloud-dataflow-package/set-package-version.sh

        jfrog rt mvn install -Pfull,asciidoctordocs,restdocs -B

        jfrog rt mvn install -pl spring-cloud-dataflow-package -B

        jfrog rt build-publish

        '
      shell: bash
      timeout-minutes: 75
    - continue-on-error: true
      if: ${{ success() || failure() }}
      name: Test Report
      uses: dorny/test-reporter@v1
      with:
        list-tests: failed
        name: Unit Tests
        path: '**/surefire-reports/*.xml'
        reporter: java-junit
    - continue-on-error: true
      if: ${{ always() }}
      name: Capture Test Results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: test-results
        path: '**/target/surefire-reports/**/*.*'
        retention-days: 7
    - continue-on-error: true
      name: Clean cache
      run: 'find ~/.m2/repository -type d -name ''*SNAPSHOT'' | xargs rm -fr

        '
  done:
    needs:
    - scan
    - build
    - images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Done
      run: echo "::info ::Done"
      shell: bash
  images:
    name: Build and Publish Images
    needs:
    - build
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
    uses: ./.github/workflows/build-images.yml
    with:
      version: ${{ needs.build.outputs.version }}
  scan:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        format: sarif
        ignore-unfixed: true
        output: trivy-results.sarif
        scan-type: fs
        severity: CRITICAL,HIGH
    - continue-on-error: true
      name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
    - continue-on-error: true
      name: Scanned
      run: echo "::info ::Scanned"
      shell: bash
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
