jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Ensure scripts are executable
      run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
      shell: bash
    - continue-on-error: true
      uses: carvel-dev/setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Login dockerhub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      id: build-package-bundle
      name: Build Package Bundle
      uses: ./.github/actions/build-package-bundle
      with:
        config: src/carvel/config
        ctr-version: ${{ inputs.ctr-version }}
        dataflow-version: ${{ inputs.dataflow-version }}
        imgpkg-lock-template: src/carvel/templates/imgpkg
        package-bundle-template: src/carvel/templates/bundle/package
        package-name: ${{ inputs.package-name }}
        project-directory: .
        server-repository: ${{ inputs.server-repository }}
        server-version: ${{ inputs.server-version }}
        skipper-repository: ${{ inputs.skipper-repository }}
        skipper-version: ${{ inputs.skipper-version }}
    - continue-on-error: true
      id: publish-package-bundle
      name: Publish Package Bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: ${{ steps.build-package-bundle.outputs.bundle-path }}
        project-directory: .
        repository: ${{ inputs.package-bundle }}
        version: ${{ inputs.package-version }}
    - continue-on-error: true
      id: build-repository-bundle
      name: Build Repository Bundle
      uses: ./.github/actions/build-repository-bundle
      with:
        package-bundle-repository: ${{ inputs.package-bundle }}
        package-name: ${{ inputs.package-name }}
        project-directory: .
        repo-bundle-template: src/carvel/templates/bundle/repo
        version: ${{ inputs.package-version }}
    - continue-on-error: true
      id: publish-repository-bundle
      name: Publish Repository Bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: ${{ steps.build-repository-bundle.outputs.bundle-path }}
        project-directory: .
        repository: ${{ inputs.repository-bundle }}
        version: ${{ inputs.package-version }}
name: common-carvel
on:
  repository_dispatch:
    types: trigger-ga___common-carvel.yml
