jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn process-resources -P deploymentfiles
    - continue-on-error: true
      name: Check Deployment Files
      uses: peter-evans/create-pull-request@v3
      with:
        assignees: ilayaperumalg
        author: SCDF Build Bot <scdf-build-bot@users.noreply.github.com>
        body: 'Detected a change with `mvn process-resources -P deploymentfiles`.


          This PR were created to align k8s deployment file changes.

          '
        branch: github-actions/update-deployment-files
        commit-message: Update k8s deployment files
        committer: SCDF Build Bot <scdf-build-bot@users.noreply.github.com>
        labels: automated pr
        reviewers: jvalkeal,ilayaperumalg
        title: Update k8s deployment files
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
name: Fix Deployment Files
on:
  repository_dispatch:
    types: trigger-ga___fix-deployment-files.yml
