jobs:
  ghrelease:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: 'BUILD_ZOO_HANDLER_spring_cloud_deployer_version

          BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version

          BUILD_ZOO_HANDLER_spring_cloud_dataflow_version

          '
    - continue-on-error: true
      name: Install Tooling
      run: 'curl -sSL https://github.com/cbroglie/mustache/releases/download/v1.2.2/mustache_1.2.2_linux_amd64.tar.gz
        | sudo tar -C /usr/local/bin/ --no-same-owner -xzv mustache

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RELEASE_NOTES_DATA: ${{runner.temp}}/release_notes_data.json
        RELEASE_NOTES_FILE: ${{runner.temp}}/release_notes.md5
        RELEASE_NOTES_FOOTERS1: ${{runner.temp}}/release_notes_footers1.json
        RELEASE_NOTES_FOOTERS2: ${{runner.temp}}/release_notes_footers2.json
        RELEASE_NOTES_FOOTERS3: ${{runner.temp}}/release_notes_footers3.json
        RELEASE_NOTES_HEADERS1: ${{runner.temp}}/release_notes_headers1.json
        RELEASE_NOTES_HEADERS2: ${{runner.temp}}/release_notes_headers2.json
        RELEASE_NOTES_HEADERS3: ${{runner.temp}}/release_notes_headers3.json
        RELEASE_NOTES_ISSUES1: ${{runner.temp}}/release_notes_issues1.json
        RELEASE_NOTES_ISSUES2: ${{runner.temp}}/release_notes_issues2.json
        RELEASE_NOTES_ISSUES3: ${{runner.temp}}/release_notes_issues3.json
        RELEASE_NOTES_PROJECT1: ${{runner.temp}}/release_notes_project1.json
        RELEASE_NOTES_PROJECT2: ${{runner.temp}}/release_notes_project2.json
        RELEASE_NOTES_PROJECT3: ${{runner.temp}}/release_notes_project3.json
      name: Release
      run: "gh issue list \\\n  --repo spring-cloud/spring-cloud-deployer \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_deployer_version \\\n  --label\
        \ automation/rlnotes-header  \\\n  --state all --json title,body \\\n  --jq\
        \ '{headers:map(.),headerslength:(length)}' \\\n  > $RELEASE_NOTES_HEADERS1\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow-ui \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version \\\n  --label\
        \ automation/rlnotes-header  \\\n  --state all --json title,body \\\n  --jq\
        \ '{headers:map(.),headerslength:(length)}' \\\n  > $RELEASE_NOTES_HEADERS2\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \\\n  --label\
        \ automation/rlnotes-header  \\\n  --state all --json title,body \\\n  --jq\
        \ '{headers:map(.),headerslength:(length)}' \\\n  > $RELEASE_NOTES_HEADERS3\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-deployer \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_deployer_version \\\n  --label\
        \ automation/rlnotes-footer  \\\n  --state all --json title,body \\\n  --jq\
        \ '{footers:map(.),footerslength:(length)}' \\\n  > $RELEASE_NOTES_FOOTERS1\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow-ui \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version \\\n  --label\
        \ automation/rlnotes-footer  \\\n  --state all --json title,body \\\n  --jq\
        \ '{footers:map(.),footerslength:(length)}' \\\n  > $RELEASE_NOTES_FOOTERS2\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \\\n  --label\
        \ automation/rlnotes-footer  \\\n  --state all --json title,body \\\n  --jq\
        \ '{footers:map(.),footerslength:(length)}' \\\n  > $RELEASE_NOTES_FOOTERS3\n\
        echo \"{\\\"name\\\":\\\"Spring Cloud Dataflow Deployer\\\",\\\"version\\\"\
        :\\\"$BUILD_ZOO_HANDLER_spring_cloud_deployer_version\\\"}\" > $RELEASE_NOTES_PROJECT1\n\
        echo \"{\\\"name\\\":\\\"Spring Cloud Dataflow UI\\\",\\\"version\\\":\\\"\
        $BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version\\\"}\" > $RELEASE_NOTES_PROJECT2\n\
        echo \"{\\\"name\\\":\\\"Spring Cloud Dataflow\\\",\\\"version\\\":\\\"$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version\\\
        \"}\" > $RELEASE_NOTES_PROJECT3\ngh issue list \\\n  --repo spring-cloud/spring-cloud-deployer\
        \ \\\n  --search milestone:$BUILD_ZOO_HANDLER_spring_cloud_deployer_version\
        \ \\\n  --state all --json number,title,labels \\\n  --jq '{issues:map(select((.labels\
        \ | length == 0) or (any(.labels[].name; startswith(\"automation/rlnotes\"\
        )|not))) + {repo:\"spring-cloud/spring-cloud-deployer\"})}' \\\n  > $RELEASE_NOTES_ISSUES1\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow-ui \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version \\\n  --state\
        \ all --json number,title,labels \\\n  --jq '{issues:map(select((.labels |\
        \ length == 0) or (any(.labels[].name; startswith(\"automation/rlnotes\")|not)))\
        \ + {repo:\"spring-cloud/spring-cloud-dataflow-ui\"})}' \\\n  > $RELEASE_NOTES_ISSUES2\n\
        gh issue list \\\n  --repo spring-cloud/spring-cloud-dataflow \\\n  --search\
        \ milestone:$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \\\n  --state\
        \ all --limit 100 --json number,title,labels \\\n  --jq '{issues:map(select((.labels\
        \ | length == 0) or (any(.labels[].name; startswith(\"automation/rlnotes\"\
        )|not))) + {repo:\"spring-cloud/spring-cloud-dataflow\"})}' \\\n  > $RELEASE_NOTES_ISSUES3\n\
        jq -s '{issues:(.[0].issues + .[1].issues + .[2].issues + .[3].issues + .[4].issues\
        \ + .[5].issues + .[6].issues + .[7].issues + .[8].issues + .[9].issues),headers:(.[10].headers\
        \ + .[11].headers + .[12].headers + .[13].headers + .[14].headers + .[15].headers\
        \ + .[16].headers + .[17].headers + .[18].headers + .[19].headers),headerslength:(.[10].headerslength\
        \ + .[11].headerslength + .[12].headerslength + .[13].headerslength + .[14].headerslength\
        \ + .[15].headerslength + .[16].headerslength + .[17].headerslength + .[18].headerslength\
        \ + .[19].headerslength),footers:(.[20].footers + .[21].footers + .[22].footers\
        \ + .[23].footers + .[24].footers + .[25].footers + .[26].footers + .[27].footers\
        \ + .[28].footers + .[29].footers), footerslength:(.[20].footerslength + .[21].footerslength\
        \ + .[22].footerslength + .[23].footerslength + .[24].footerslength + .[25].footerslength\
        \ + .[26].footerslength + .[27].footerslength + .[28].footerslength + .[29].footerslength),projects:{spring_cloud_dataflow_build:{name:\"\
        Spring Cloud Dataflow Build\",version:(.[30].version)},spring_cloud_dataflow_common:{name:\"\
        Spring Cloud Dataflow Common\",version:(.[31].version)},spring_cloud_deployer:{name:\"\
        Spring Cloud Deployer\",version:(.[32].version)},spring_cloud_deployer_local:{name:\"\
        Spring Cloud Deployer Local\",version:(.[33].version)},spring_cloud_deployer_cloudfoundry:{name:\"\
        Spring Cloud Deployer CF\",version:(.[34].version)},spring_cloud_deployer_kubernetes:{name:\"\
        Spring Cloud Deployer K8S\",version:(.[35].version)},spring_cloud_common_security_config:{name:\"\
        Spring Cloud Common Security Config\",version:(.[36].version)},spring_cloud_skipper:{name:\"\
        Spring Cloud Skipper\",version:(.[37].version)},spring_cloud_dataflow_ui:{name:\"\
        Spring Cloud Dataflow UI\",version:(.[38].version)},spring_cloud_dataflow:{name:\"\
        Spring Cloud Dataflow\",version:(.[39].version)}}}' \\\n  $RELEASE_NOTES_ISSUES1\
        \ $RELEASE_NOTES_ISSUES2 $RELEASE_NOTES_ISSUES3 \\\n  $RELEASE_NOTES_HEADERS1\
        \ $RELEASE_NOTES_HEADERS2 $RELEASE_NOTES_HEADERS3 \\\n  $RELEASE_NOTES_FOOTERS1\
        \ $RELEASE_NOTES_FOOTERS2 $RELEASE_NOTES_FOOTERS3 \\\n  $RELEASE_NOTES_PROJECT1\
        \ $RELEASE_NOTES_PROJECT2 $RELEASE_NOTES_PROJECT3 \\\n  > $RELEASE_NOTES_DATA\n\
        mustache $RELEASE_NOTES_DATA .github/rlnotes.mustache > $RELEASE_NOTES_FILE\n\
        gh release create v$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \\\n \
        \ --draft \\\n  --title \"Spring Cloud Data Flow $BUILD_ZOO_HANDLER_spring_cloud_dataflow_version\"\
        \ \\\n  --notes-file $RELEASE_NOTES_FILE\n# retrieve spring-cloud-dataflow-package\
        \ and upload to github release\nexport PACKAGE_VERSION=${$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version}\n\
        pushd spring-cloud-dataflow-package \n  ./set-package-version.sh\n  ../mvnw\
        \ package\npopd\nPACKAGE_FILE=\"./spring-cloud-dataflow-package/target/spring-cloud-dataflow-oss-install-${PACKAGE_VERSION}.zip\"\
        \          \ngh release upload v$PACKAGE_VERSION $PACKAGE_FILE --clobber\n"
    - continue-on-error: true
      name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"ghrelease-succeed\"\
          \n}\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Notify Build Failure Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"ghrelease-failed\"\
          \n}\n"
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
name: Github Release
on:
  repository_dispatch:
    types: trigger-ga___github-release.yml
