jobs:
  labeler:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Handle Issues
      uses: jvalkeal/issue-handler@v0.0.4
      with:
        config: "{\n  \"data\": {\n    \"team\": [\n      \"jvalkeal\",\n      \"\
          oodamien\",\n      \"ilayaperumalg\",\n      \"sabbyanandan\",\n      \"\
          tzolov\",\n      \"chrisjs\",\n      \"cppwfs\",\n      \"mminella\",\n\
          \      \"dturanski\",\n      \"onobc\",\n      \"claudiahub\",\n      \"\
          sobychacko\",\n      \"corneil\"\n    ]\n  },\n  \"recipes\": [\n    {\n\
          \      \"name\": \"Mark new issue to get triaged\",\n      \"type\": \"\
          ifThen\",\n      \"if\": \"isAction('opened') && !dataInArray('team', actor)\"\
          ,\n      \"then\": \"labelIssue(['status/need-triage'])\"\n    },\n    {\n\
          \      \"name\": \"Switch to team if user comments\",\n      \"type\": \"\
          ifThen\",\n      \"if\": \"isEvent('issue_comment') && isAction('created')\
          \ && actor == context.payload.issue.user.login && labelsContainsAny('status/need-feedback')\"\
          ,\n      \"then\": \"[labelIssue('for/team-attention'), removeLabel('status/need-feedback')]\"\
          \n    },\n    {\n      \"name\": \"Switch to user if team comments\",\n\
          \      \"type\": \"ifThen\",\n      \"if\": \"isEvent('issue_comment') &&\
          \ isAction('created') && dataInArray('team', actor) && labelsContainsAny('for/team-attention')\
          \ \",\n      \"then\": \"[labelIssue('status/need-feedback', removeLabel('for/team-attention'))]\"\
          \n    },\n    {\n      \"name\": \"Manage backport issues\",\n      \"type\"\
          : \"manageBackportIssues\",\n      \"whenLabeled\": \"labeledStartsWith(['branch/'])\"\
          ,\n      \"whenUnlabeled\": \"labeledStartsWith(['branch/'])\",\n      \"\
          whenLabels\": \"labelsContainsAny(['for/backport'])\",\n      \"fromLabels\"\
          : \"labeledStartsWith(['branch/'])\",\n      \"additionalLabels\": \"'type/backport'\"\
          ,\n      \"body\": \"'Backport #' + number\"\n    }\n  ]\n}\n"
        token: ${{ secrets.GITHUB_TOKEN }}
name: Issue Handler
on:
  repository_dispatch:
    types: trigger-ga___issue-handler.yml
