env:
  MAVEN_THREADS: -T 0.5C
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2-

          '
    - continue-on-error: true
      name: Configure JFrog Cli
      run: "jfrog rt mvnc \\\n  --server-id-resolve=repo.spring.io \\\n  --server-id-deploy=repo.spring.io\
        \ \\\n  --repo-resolve-releases=libs-milestone \\\n  --repo-resolve-snapshots=libs-snapshot\
        \ \\\n  --repo-deploy-releases=libs-milestone-local \\\n  --repo-deploy-snapshots=libs-snapshot-local\n\
        echo JFROG_CLI_BUILD_NAME=spring-cloud-dataflow-main-milestone >> $GITHUB_ENV\n\
        echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: 'BUILD_ZOO_HANDLER_milestone_version

          BUILD_ZOO_HANDLER_spring_cloud_deployer_version

          BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version

          '
    - continue-on-error: true
      name: Build and Publish
      run: "jfrog rt mvn build-helper:parse-version versions:set \\\n  -gs .github/settings.xml\
        \ \\\n  -Pstagingmilestone \\\n  -DprocessAllModules=true \\\n  -DgenerateBackupPoms=false\
        \ \\\n  -Dartifactory.publish.artifacts=false \\\n  -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-'${BUILD_ZOO_HANDLER_milestone_version}\
        \ \\\n  -B\nBUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$(mvn help:evaluate\
        \ -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version\
        \ >> $GITHUB_ENV\necho \"::notice ::set dataflow.version=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_version}\"\
        \        \njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml\
        \ \\\n  -Pstagingmilestone \\\n  -DgenerateBackupPoms=false \\\n  -Dproperty=dataflow.version\
        \ \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_version} \\\
        \n  -B        \njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml\
        \ \\\n  -Pstagingmilestone \\\n  -DgenerateBackupPoms=false \\\n  -Dproperty=spring-cloud-deployer.version\
        \ \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_version} \\\
        \n  -B\njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml\
        \ \\\n  -Pstagingmilestone \\\n  -DgenerateBackupPoms=false \\\n  -Dproperty=spring-cloud-dataflow-ui.version\
        \ \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version}\
        \ \\\n  -B\njfrog rt build-clean\n./spring-cloud-dataflow-package/set-package-version.sh\n\
        jfrog rt mvn -gs .github/settings.xml -Pstagingmilestone,full,deploymentfiles\
        \ -B install -DskipTests \njfrog rt build-publish\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$(mvn\
        \ -gs .github/settings.xml -Pstagingmilestone help:evaluate -Dexpression=project.version\
        \ -q -DforceStdout) >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname=spring-cloud-dataflow-main-milestone\
        \ >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber=$GITHUB_RUN_NUMBER\
        \ >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Tag Release
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        tag-release-branch: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
          }}
        tag-release-tag: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        tag-release-tag-prefix: v
    - continue-on-error: true
      name: Build and Publish Images
      uses: ./.github/actions/build-images
      with:
        GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
        dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
    - continue-on-error: true
      name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"build-succeed\"\n\
          }\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Notify Build Failure Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"build-failed\",\n\
          \  \"message\": \"spring-cloud-dataflow failed\"\n}\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
    - continue-on-error: true
      name: Clean cache
      run: 'find ~/.m2/repository -type d -name ''*SNAPSHOT'' | xargs rm -fr

        '
name: Milestone Worker
on:
  repository_dispatch:
    types: trigger-ga___milestone-worker.yml
