jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Handle Zoo Control
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-config: "[\n  {\n    \"if\": \"initial == true\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-deployer\",\n\
          \      \"ref\": \"2.11.x\",\n      \"workflow\": \"next-dev-version-worker.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'next-dev-version-succeed'\
          \ && data.repo == 'spring-cloud-deployer' && data.owner == 'spring-cloud'\"\
          ,\n    \"action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n\
          \      \"owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow-ui\"\
          ,\n      \"ref\": \"2.11.x\",\n      \"workflow\": \"next-dev-version-worker.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'next-dev-version-succeed'\
          \ && data.repo == 'spring-cloud-dataflow-ui' && data.owner == 'spring-cloud'\"\
          ,\n    \"action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n\
          \      \"owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\"\
          ,\n      \"ref\": \"2.11.x\",\n      \"workflow\": \"next-dev-version-worker.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'next-dev-version-failed'\"\
          ,\n    \"action\": \"fail\",\n    \"fail\": {\n      \"message\": \"hi,\
          \ something went wrong\"\n    }\n  }\n]\n"
        dispatch-handler-max: 15
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
name: Next Dev Version Controller
on:
  repository_dispatch:
    types: trigger-ga___next-dev-version-controller.yml
