jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Handle Zoo Control
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-config: "[\n  {\n    \"if\": \"initial == true\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-deployer\",\n\
          \      \"ref\": \"2.9.x\",\n      \"workflow\": \"release-worker.yml\"\n\
          \    }\n  },\n  {\n    \"if\": \"data.event == 'build-succeed' && data.repo\
          \ == 'spring-cloud-deployer' && data.owner == 'spring-cloud'\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow-ui\"\
          ,\n      \"ref\": \"3.4.x\",\n      \"workflow\": \"release-worker.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'build-succeed' && data.repo\
          \ == 'spring-cloud-dataflow-ui' && data.owner == 'spring-cloud'\",\n   \
          \ \"action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n   \
          \   \"owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\"\
          ,\n      \"ref\": \"2.11.x\",\n      \"workflow\": \"release-worker.yml\"\
          \n    }\n  },\n  { \n    \"if\": \"data.event == 'build-succeed' && data.repo\
          \ == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\",\n\
          \      \"ref\": \"2.11.x\",\n      \"workflow\": \"carvel-worker.yml\"\n\
          \    }            \n  },\n  {\n    \"if\": \"data.event == 'carvel-succeed'\
          \ && data.repo == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'\"\
          ,\n    \"action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n\
          \      \"owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\"\
          ,\n      \"ref\": \"2.11.x\",\n      \"workflow\": \"promote-release.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'promote-succeed' && data.repo\
          \ == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\",\n\
          \      \"ref\": \"2.11.x\",\n      \"workflow\": \"central-release.yml\"\
          \n    }\n  },\n  {\n    \"if\": \"data.event == 'central-succeed' && data.repo\
          \ == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'\",\n    \"\
          action\": \"workflow_dispatch\",\n    \"workflow_dispatch\": {\n      \"\
          owner\": \"spring-cloud\",\n      \"repo\": \"spring-cloud-dataflow\",\n\
          \      \"ref\": \"2.11.x\",\n      \"workflow\": \"github-release.yml\"\n\
          \    }\n  },\n  {\n    \"if\": \"data.event == 'promotion-failed'\",\n \
          \   \"action\": \"fail\",\n    \"fail\": {\n      \"message\": \"artifactory\
          \ promotion failed\"\n    }\n  },\n  {\n    \"if\": \"data.event == 'central-failed'\"\
          ,\n    \"action\": \"fail\",\n    \"fail\": {\n      \"message\": \"central\
          \ sync failed\"\n    }\n  },\n  {\n    \"if\": \"data.event == 'ghrelease-failed'\"\
          ,\n    \"action\": \"fail\",\n    \"fail\": {\n      \"message\": \"github\
          \ release failed\"\n    }\n  },\n  {\n    \"if\": \"data.event == 'build-failed'\"\
          ,\n    \"action\": \"fail\",\n    \"fail\": {\n      \"message\": \"something\
          \ went wrong in build train\"\n    }\n  }\n]\n"
        dispatch-handler-max: 20
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
name: Release Controller
on:
  repository_dispatch:
    types: trigger-ga___release-controller.yml
