env:
  MAVEN_THREADS: -T 1
jobs:
  build:
    outputs:
      BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname
        }}
      BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber
        }}
      BUILD_ZOO_HANDLER_spring_cloud_dataflow_version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
        }}
      BUILD_ZOO_HANDLER_spring_cloud_skipper_version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version
        }}
      version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      uses: jvalkeal/setup-maven@v1
      with:
        maven-mirror: https://dlcdn.apache.org/maven/maven-3/
        maven-version: 3.8.8
    - continue-on-error: true
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2-

          '
    - continue-on-error: true
      name: Configure JFrog Cli
      run: "jfrog rt mvnc \\\n  --server-id-resolve=repo.spring.io \\\n  --server-id-deploy=repo.spring.io\
        \ \\\n  --repo-resolve-releases=libs-release-staging \\\n  --repo-resolve-snapshots=libs-snapshot\
        \ \\\n  --repo-deploy-releases=libs-staging-local \\\n  --repo-deploy-snapshots=libs-snapshot-local\n\
        echo JFROG_CLI_BUILD_NAME=spring-cloud-dataflow-main-release >> $GITHUB_ENV\n\
        echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: 'BUILD_ZOO_HANDLER_spring_cloud_deployer_version

          BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version

          '
    - continue-on-error: true
      name: Build and Publish
      run: "jfrog rt mvn build-helper:parse-version versions:set \\\n  -gs .github/settings.xml\
        \ \\\n  -Pstagingrelease \\\n  -DskipResolution=true \\\n  -DprocessAllModules=true\
        \ \\\n  -DgenerateBackupPoms=false \\\n  -Dartifactory.publish.artifacts=false\
        \ \\\n  -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'\
        \ \\\n  -B\nBUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$(mvn help:evaluate\
        \ -Dexpression=project.version -q -DforceStdout)\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version\
        \ >> $GITHUB_ENV\necho \"::notice ::set dataflow.version=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_version}\"\
        \njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml \\\n \
        \ -Pstagingrelease \\\n  -DskipResolution=true \\\n  -DgenerateBackupPoms=false\
        \ \\\n  -Dproperty=dataflow.version \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_version}\
        \ \\\n  -B             \necho \"::notice ::set spring-cloud-deployer.version=${BUILD_ZOO_HANDLER_spring_cloud_deployer_version}\"\
        \njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml \\\n \
        \ -Pstagingrelease \\\n  -DskipResolution=true \\\n  -DgenerateBackupPoms=false\
        \ \\\n  -Dproperty=spring-cloud-deployer.version \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_version}\
        \ \\\n  -B\necho \"::notice ::set spring-cloud-dataflow-ui.version=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version}\"\
        \njfrog rt mvn versions:set-property \\\n  -gs .github/settings.xml \\\n \
        \ -DskipResolution=true \\\n  -Pstagingrelease \\\n  -DgenerateBackupPoms=false\
        \ \\\n  -Dproperty=spring-cloud-dataflow-ui.version \\\n  -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version}\
        \ \\\n  -B\necho \"::notice ::build-clean\"\njfrog rt build-clean\necho \"\
        ::notice ::set-package-version\"\n./spring-cloud-dataflow-package/set-package-version.sh\n\
        echo \"::notice ::install\"\njfrog rt mvn -gs .github/settings.xml -Pstagingrelease,full,deploymentfiles\
        \ -B install -DskipTests\necho \"::notice ::build-publish\"\njfrog rt build-publish\n\
        spring_cloud_dataflow_version=$(mvn -gs .github/settings.xml -Pstagingrelease\
        \ help:evaluate -Dexpression=project.version -q -DforceStdout)\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$spring_cloud_dataflow_version\
        \ >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname=spring-cloud-dataflow-main-release\
        \ >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber=$GITHUB_RUN_NUMBER\
        \ >> $GITHUB_ENV\necho BUILD_ZOO_HANDLER_spring_cloud_skipper_version=$spring_cloud_dataflow_version\
        \ >> $GITHUB_ENV\n\necho \"::info ::BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=$spring_cloud_dataflow_version\"\
        \ \necho \"::info ::BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname=spring-cloud-dataflow-main-release\"\
        \ \necho \"::info ::BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber=$GITHUB_RUN_NUMBER\"\
        \ \necho \"::info ::BUILD_ZOO_HANDLER_spring_cloud_skipper_version=$spring_cloud_dataflow_version\"\
        \n"
    - continue-on-error: true
      name: Tag Release
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        tag-release-branch: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
          }}
        tag-release-tag: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        tag-release-tag-prefix: v
    - continue-on-error: true
      name: Clean cache
      run: 'find ~/.m2/repository -type d -name ''*SNAPSHOT'' | xargs rm -fr

        '
  images:
    name: Build and Publish Images
    needs:
    - build
    secrets:
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
    uses: ./.github/workflows/build-images.yml
    with:
      version: ${{ needs.build.outputs.version }}
  wrap:
    needs:
    - build
    - images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ success() }}
      name: Save env
      run: "echo \"BUILD_ZOO_HANDLER_spring_cloud_dataflow_version=${{ needs.build.outputs.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version\
        \ }}\" >> $GITHUB_ENV\necho \"BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname=${{\
        \ needs.build.outputs.BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildname }}\"\
        \ >> $GITHUB_ENV \necho \"BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber=${{\
        \ needs.build.outputs.BUILD_ZOO_HANDLER_spring_cloud_dataflow_buildnumber\
        \ }}\" >> $GITHUB_ENV\necho \"BUILD_ZOO_HANDLER_spring_cloud_skipper_version=${{\
        \ needs.build.outputs.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}\"\
        \ >> $GITHUB_ENV\n"
      shell: bash
    - continue-on-error: true
      if: ${{ success() }}
      name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"build-succeed\"\n\
          }\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Notify Build Failure Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-client-payload-data: "{\n  \"event\": \"build-failed\",\n\
          \  \"message\": \"spring-cloud-dataflow failed\"\n}\n"
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
name: Release Worker
on:
  repository_dispatch:
    types: trigger-ga___release-worker.yml
