jobs:
  schedule:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: benc-uk/workflow-dispatch@v1
      with:
        ref: ${{ matrix.branch }}
        token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        workflow: Build Snapshot Controller
    strategy:
      matrix:
        branch:
        - main
        - 2.10.x
name: Schedule Snapshot Train Builds
on:
  repository_dispatch:
    types: trigger-ga___schedule-train-builds.yml
